#################################################################
## Home Assistant
#################################################################

homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: imperial
  time_zone: !secret homeassistant_timezone
#  customize: !include_dir_merge_named customize
  packages: !include_dir_named packages

frontend:
  javascript_version: latest

updater:
  reporting: no
  include_used_components: true

#map:
discovery:

logger:
  default: error
#  logs:
#    homeassistant.components.konnected: debug
#     homeassistant.components.tts: debug

recorder:
  purge_keep_days: 5
history:
logbook:
conversation:

#cloud:
ffmpeg:
config:
sun:

http:
  base_url: !secret http_base_url
  # server_port: !secret http_port
  api_password: !secret http_api_password
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 10.50.21.0/24
  ip_ban_enabled: True
  login_attempts_threshold: 5

google_assistant:
  project_id: !secret google_assistant_project_id
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  #agent_user_id: [a string to identify user]
  api_key: !secret google_assistant_api_key
  exposed_domains:
    - switch
    - light
  entity_config:
    switch.front_hallway_switch:
      name: Front Hallway
      #aliases:
      #  - bright lights
      #  - entry lights
    switch.siren:
      expose: false

tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300


notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_chris_api
  - name: pushbullet_diona
    platform: pushbullet
    api_key: !secret pushbullet_diona_api
  - name: all
    platform: group
    services:
      - service: pushbullet
      - service: pushbullet_diona

group: !include group.yaml
script: !include_dir_merge_named script
#sensor: !include_dir_merge_list sensor
#automation: !include_dir_merge_list automation

#camera: !include camera.yaml
