####################################################
#                                                  #
# This package creates a device that monitors who  #
# is at home, including a guest mode, and provides #
# modes that assist with automations.              #
#                                                  #
####################################################


homeassistant:
  customize:
    sensor.home_status:
      icon: mdi:home-map-marker



device_tracker:
#  - platform: gpslogger
 - platform: unifi
   host: !secret unifi_host
   username: !secret unifi_username
   password: !secret unifi_password
   verify_ssl: False


input_boolean:
  away_mode:

  guest_mode:
    name: Guest mode
    icon: mdi:human-handsup

  holiday_mode:
    name: Holiday mode
    icon: mdi:airplane

  bathtime_mode:
    name: Bathtime mode
    icon: mdi:hot-tub

  bedtime_mode:
    name: Bedtime mode
    icon: mdi:sleep


sensor:
  platform: template
  sensors:
    home_status:
      friendly_name: Home status
      value_template: >
        {% if is_state('group.phone_trackers' , 'home') or is_state('input_boolean.guest_mode' , 'on') %}Occupied
        {% else %} Unoccupied {% endif %}


group:
  Phone trackers:
    - device_tracker.oneplus3_chris
    - device_tracker.oneplus3_diona

  Adults:
    - device_tracker.oneplus3_chris
    - device_tracker.oneplus3_diona

  Occupancy:
    name: ' '
    control: hidden
    entities:
      - alarm_control_panel.alarm
      - sensor.home_status
      - lock.front_door_locked
      - input_boolean.guest_mode
      - input_boolean.holiday_mode
      - group.all_automations
      - input_boolean.bathtime_mode
      - input_boolean.bedtime_mode

alert:
  guest_mode_alert:
    name: Guest Mode has been on for a long time
    done_message: Guest Mode de-activated
    entity_id: input_boolean.guest_mode
    repeat:
      - 240
      - 120
    skip_first: true
    notifiers:
      - adults

  bathtime_mode_alert:
    name: Bathtime Mode has been on for a long time
    done_message: Bathtime Mode de-activated
    entity_id: input_boolean.bathtime_mode
    repeat: 60
    skip_first: true
    notifiers:
      - adults


automation:
  - alias: Occupancy - Return home
    initial_state: on
    trigger:
      platform: state
      entity_id: group.phone_trackers
      to: 'home'
    action:
      service: homeassistant.turn_off
      entity_id:
        - input_boolean.guest_mode
        - input_boolean.away_mode
        - input_boolean.holiday_mode

  - alias: Occupancy - Nobody home
    initial_state: on
    trigger:
      platform: state
      entity_id: sensor.home_status
      to: 'Unoccupied'
      for:
        minutes: 2
    action:
      - service: homeassistant.turn_off
        entity_id:
          - group.all_lights
      - service: homeassistant.turn_on
        entity_id:
          - input_boolean.away_mode

  - alias: Occupancy - Holiday Mode
    initial_state: on
    trigger:
      platform: state
      entity_id: input_boolean.away_mode
      to: 'on'
      for:
        hours: 24
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.holiday_mode
      - service: homeassistant.turn_off
        entity_id: input_boolean.away_mode
