automation:
  - alias: 'Recycle Night'
    trigger:
      - platform: time
        at: '19:15:00'
    condition:
      - condition: template
        value_template: >
          {% set val = now() %}
          {{ not( ((val.strftime("%a")=="Sat" ) or (val.strftime("%a")=="Sun" )) and (((val.isocalendar()[1])%2)==1))  }}
    action:
    #  - wait_template: "{{ is_state('group.adults' , 'home') }}"
    #    timeout: 14:00:00
    #  - delay: 00:15:00
      - service: script.speech_engine
        data:
          call_recycle_night: 1

  - alias: 'Garbage Night'
    trigger:
      - platform: time
        at: '19:15:00'
    action:
    #  - wait_template: "{{ is_state('group.adults' , 'home') }}"
    #    timeout: 14:00:00
    #  - delay: 00:15:00
      - service: script.speech_engine
        data:
          call_garbage_night: 1

group:
  Reminder Automations:
     entities:
       - automation.garbage_night
       - automation.recycle_night
